spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.60.129:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null  #不序列化对象里为空的字段


server:
  context-path: /sell  #访问项目url接口前缀

wechat:
  appId: wx1a67eaa5669d999a
  appSecret: 0dcdaad4b0b6ea8545f3f8881ca230f5